---
title: "Picasso Dashboard"
subtitle: "Home"

header: false
footer: '<p><a href="https://github.com/cityplug?tab=repositories"><i class="fab fa-github-alt"></i></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="https://redi1.soccerstreams.net/"><i class="fas fa-futbol"></i></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="https://www3.gogoanime.cm/category/shingeki-no-kyojin-the-final-season-part-2"><i class="fas fa-dragon"></i></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="https://anydesk.com/uk/downloads/thank-you?dv=win_exe"><i class="fas fa-download"></i></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="https://dash.cloudflare.com/login/"><i class="fa-brands fa-cloudflare"></i></a></p>'
target: "_blank" # optional html a tag target attribute

stylesheet:
  - "assets/custom.css"

columns: "4" # Change this to any number: (1, 2, 3, 4, 6, 12)
colors:
  dark:
    highlight-primary: "#181C3A"
    highlight-secondary: "#181C3A"
    highlight-hover: "#1F2347"
    background: "#12152B"
    card-background: "#181C3A"
    text: "#EAEAEA"
    text-header: "#7C71DD"
    text-title: "#C1C1C1"
    text-subtitle: "#8B8D9C"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#C1C1C1"
    link-hover: "#C1C1C1"
    background-image: "../assets/wallpaper.jpeg"

  light:
    highlight-primary: "#181C3A"
    highlight-secondary: "#181C3A"
    highlight-hover: "#1F2347"
    background: "#12152B"
    card-background: "#181C3A"
    text: "#EAEAEA"
    text-header: "#7C71DD"
    text-title: "#C1C1C1"
    text-subtitle: "#8B8D9C"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#C1C1C1"
    link-hover: "#C1C1C1"
    background-image: "../assets/wallpaper.jpeg"

links:
 - name: "Google.co.uk"
   icon: "fas fa-search"
   url: "https://www.google.co.uk/?gws_rd=ssl"
   target: "_blank" # optional html a tag target attribute

services:
  - name: "//Services"
    icon: "fa-solid fa-gears"
    items:
      - name: "Shell"
        logo: "assets/tools/shell.png"
        subtitle: "Server Management GUI"
        tag: "service"
        tagstyle: "is-success"
        url: "https://192.168.50.250:9090/"
        target: "_blank" # optional html a tag target attribute
      - name: "Picasso.Pihole"
        logo: "assets/tools/pihole.png"
        subtitle: "DNS"
        tag: "service"
        tagstyle: "is-success"
        url: "http://192.168.50.250/admin/"
        target: "_blank" # optional html a tag target attribute

  - name: "//Management"
    icon: "fa-solid fa-folder-open"
    items:
      - name: "Reolink"
        logo: "assets/tools/reo.png"
        subtitle: "Docker UI"
        tag: "core"
        tagstyle: "is-link"
        url: "http://192.168.50.250:9000/#!/auth"
        target: "_blank" # optional html a tag target attribute