version: "3"

networks:
  pico_net:
    external: true

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    environment:
      TZ: Europe/London
      WEBPASSWORD:
      ServerIP: 192.168.7.253
    hostname: pico.pihole
    volumes:
      - /pico/.AppData/pihole:/etc/pihole/
      - /pico/.AppData/pihole/dnsmasq:/etc/dnsmasq.d/
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      pico_net:
        ipv4_address: 192.168.7.253

  unbound:
    container_name: unbound
    image: mvance/unbound:latest
    volumes:
      - /pico/.AppData/unbound:/opt/unbound/etc/unbound/
    ports:
      - 5335:53/upd
      - 5335:53/tcp
    restart: always

  cloudflare-ddns:
    container_name: cloudflareDNS
    image: oznu/cloudflare-ddns
    restart: always
    environment:
      PUID: 0
      PGID: 0
      API_KEY: ktez6xlMnDf0yaD5xGuUjgI-PV95A2Dn3tohz6wV
      ZONE: cityplug.co.uk
      SUBDOMAIN: home.astarpainters.co.uk

  homer:
    container_name: homer
    image: b4bz/homer:latest
    hostname: homer  
    volumes:
      - /pico/.AppData/homer/assets:/www/assets
    ports:
      - 85:8080
    restart: always

  zerotier:
    container_name: zerotier
    image: zyclonite/zerotier:latest
    devices:
      - /dev/net/run
    network_mode: host
    volumes:
      - /pico/.AppData/zerotier:/var/lib/zerotier-one
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN

  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser:latest
    user: 0:0
    volume: 
      - /pico/:/srv
    ports:
      - 8222:80
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

  homebridge:
    image: oznu/homebridge:latest
    container_name: homebridge
    restart: always
    network_mode: host
    environment:
      - TZ=Europe/London
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=7471
    volumes:
      - /pico/.AppData/homebridge:/homebridge
      
  watchtower:
      image: containrrr/watchtower
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      environment: 
        - WATCHTOWER_CLEANUP=true
        - WATCHTOWER_LABEL_ENABLE=true
        - WATCHTOWER_INCLUDE_STOPPED=true
        - WATCHTOWER_REVIVE_STOPPED=true
        - WATCHTOWER_POLL_INTERVAL=604800